fir_notifications/urls.py
from django.conf.urls import url

from fir_notifications import views


urlpatterns = [
    url(r'^subscriptions$', views.subscriptions, name='subscriptions'),
    url(r'^subscriptions/(?P<object_id>\d+)$', views.edit_subscription, name='edit-subscription'),
    url(r'^subscriptions/subscribe$', views.edit_subscription, name='subscribe'),
    url(r'^subscriptions/(?P<object_id>\d+)/unsubscribe$', views.unsubscribe, name='unsubscribe'),
    url(r'^method/(?P<method>[a-zA-Z0-9_]+)$', views.method_configuration, name='method_configuration'),
]

fir_notifications/forms.py
import json

from django import forms
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth import get_user_model

from incidents.models import BusinessLine

from fir_notifications.registry import registry
from fir_notifications.models import MethodConfiguration, NotificationPreference


class MethodConfigurationForm(forms.Form):
    def __init__(self, *args, **kwargs):
        self.method = kwargs.pop('method')
        self.user = kwargs.pop('user', None)
        super(MethodConfigurationForm, self).__init__(*args, **kwargs)
        for option_id, option_field in self.method.options.items():
            self.fields[option_id] = option_field
        self.title = _("Configure %(method)s" % {'method': self.method.verbose_name})

    def save(self, *args, **kwargs):
        if self.user is None:
            return None
        json_value = json.dumps(self.cleaned_data)
        config, created = MethodConfiguration.objects.update_or_create(user=self.user, key=self.method.name,
                                                                       defaults={'value': json_value})
        return config


class NotificationTemplateForm(forms.ModelForm):
    event = forms.ChoiceField(choices=registry.get_event_choices())

    class Meta:
        fields = '__all__'


class NotificationPreferenceForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        instance = kwargs.get('instance', None)
        if self.user is None and instance is not None:
            self.user = instance.user
        if instance is None and kwargs.get('data', None) is not None:
            data = kwargs.get('data')
            event = data.get('event', None)
            method = data.get('method', None)
            if event and method and self.user:
                try:
                    kwargs['instance'] = NotificationPreference.objects.get(user=self.user, event=event, method=method)
                except (NotificationPreference.DoesNotExist, NotificationPreference.MultipleObjectsReturned):
                    pass
        super(NotificationPreferenceForm, self).__init__(*args, **kwargs)
        self.fields['business_lines'].queryset = BusinessLine.authorization.for_user(self.user,
                                                                                     'incidents.view_incidents')
        if instance is not None:
            self.fields['event'].disabled = True
            self.fields['method'].disabled = True

    def clean_user(self):
        if self.user is None:
            raise forms.ValidationError(_("Notification preference must be linked to a user."))
        return self.user

    user = forms.ModelChoiceField(queryset=get_user_model().objects.all(), widget=forms.HiddenInput(), required=False)
    event = forms.ChoiceField(choices=registry.get_event_choices(), label=_('Event'))
    method = forms.ChoiceField(choices=registry.get_method_choices(), label=_('Method'))
    business_lines = forms.ModelMultipleChoiceField(BusinessLine.objects.all(), label=_('Business lines'))

    class Meta:
        fields = '__all__'
        model = NotificationPreference

fir_notifications/templates/fir_notifications/actions.html
{% load i18n %}
{% for method, method_name in actions.items %}
<li><a href="#" id="user_configure_{{method}}" data-toggle='modal' data-target='#configure_{{method}}'><i class="glyphicon glyphicon-comment"></i>{% blocktrans %}Configure {{ method_name }}{% endblocktrans %}</a></li>
{% endfor %}

fir_notifications/templates/fir_notifications/actions_form.html
{% load i18n %}
{% load add_css_class %}

{% for method, method_form in actions.items %}
    <div id="configure_{{method}}" class="modal fade notification-method-form" tabindex="-1" role="dialog" aria-labelledby="configure_{{method}}_label" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <form id="configure_{{method}}_form" method="POST" action="{% url 'notifications:method_configuration' method %}">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        <h4 id="configure_{{method}}_label" class="modal-title">{{method_form.title}}</h4>
                    </div>
                    <div class="modal-body">
                        <div>
                            {% csrf_token %}
                            {% for field in method_form %}
                            <div class="form-group row">
                                <div class="col-sm-4">
                                    {{ field.label_tag }}
                                </div>
                                <div class="col-sm-8">
                                    {{ field|add_css_class:"form-control" }}
                                    <span class='help-block'>
                                        {% if not field.errors and field.help_text %}
                                            {{field.help_text}}
                                        {% endif %}
                                        {% for error in field.errors %}
                                            {{error}}
                                        {% endfor %}
                                    </span>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>

                    <div class="modal-footer">
                        <button class="btn btn-default" data-dismiss="modal" aria-hidden="true">{%  trans "Cancel" %}</button>
                        <button type="submit" class="btn btn-primary">{%  trans "Save" %}</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endfor %}
<script>
        window.onload = function(){
            $('.notification-method-form').on('fir.form.success', function (event) {
                console.log(this);
                $(this).modal('hide');
                event.stopPropagation();
            });
        };
    </script>

fir_notifications/templates/fir_notifications/preferences.html
{% load i18n %}
{% load add_css_class %}

{% if formset.forms %}
<div class="col-sm-8 col-sm-offset-2">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">{% trans "Notification preferences" %}</h3>
      </div>
      <div class="panel-body">
          <form action="{% url 'notifications:preferences' %}" method="post">
                <div class="row-fluid">
                    {% csrf_token %}
                    {{ formset.management_form }}
                    {% for label, forms in formset.labelled_forms.items %}
                    <fieldset>
                        <legend>{{ label }}</legend>
                        {% for form in forms %}
                        <div class="col-sm-3">
                            <div class="form-group">
                           <label id="id_business_lines">{{ form.get_notification_display }}</label>
                                {{ form.business_lines|add_css_class:"form-control" }}
                                {% for hidden in form.hidden_fields %}
                                    {{ hidden }}
                                {% endfor %}
                            </div>
                        </div>
                        {% endfor %}
                    </fieldset>
                    {% endfor %}
                </div>
                <div class="row-fluid">
                    <button class="btn btn-primary" type="submit">{% trans "Save" %}</button>
                </div>
            </form>
        </div>
      </div>
</div>
{% endif %}

fir_notifications/templates/fir_notifications/subscribe.html
{% load  add_css_class %}
{% load i18n %}
<div id="subscribe_notifications" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="subscribe_notifications}_label" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <form id="subscribe_notifications_form" method="POST" action="{{ request.path }}">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 id="subscribe_notifications_label" class="modal-title">{% trans "Notification subscription" %}</h4>
                </div>
                <div class="modal-body">
                    <div>
                        {% csrf_token %}

                        {% for hidden in form.hidden_fields %}
                            {{ hidden }}
                        {% endfor %}

                        {% for field in form.visible_fields %}
                        <div class="form-group row">
                            <div class="col-sm-4">
                                {{ field.label_tag }}
                            </div>
                            <div class="col-sm-8">
                                {{ field|add_css_class:"form-control" }}
                                <span class='help-block'>
                                    {% if not field.errors and field.help_text %}
                                        {{field.help_text}}
                                    {% endif %}
                                    {% for error in field.errors %}
                                        {{error}}
                                    {% endfor %}
                                </span>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>

                <div class="modal-footer">
                    <button class="btn btn-default" data-dismiss="modal" aria-hidden="true">{%  trans "Cancel" %}</button>
                    <button type="submit" class="btn btn-primary">{%  trans "Save" %}</button>
                </div>
            </form>
        </div>
    </div>
</div>

fir_notifications/templates/fir_notifications/subscriptions.html
{% load i18n %}
{% load notifications %}
{% load staticfiles %}

<div class="col-sm-8 col-sm-offset-2">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">{% trans "Notification subscriptions" %}</h3>
      </div>
      <div class="panel-body">
          <table class="table table-condensed">
            <thead>
                <tr>
                    <th>{%  trans "Section" %}</th>
                    <th>{%  trans "Event" %}</th>
                    <th>{%  trans "Method" %}</th>
                    <th>{%  trans "Business lines" %}</th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
              {% for preference in preferences %}
                  <tr>
                    <td>{{ preference.event|display_event_section }}</td>
                    <td>{{ preference.event|display_event }}</td>
                    <td>{{ preference.method|display_method }}</td>
                    <td>{{ preference.business_lines.all|join:', ' }}</td>
                      <td><a href="#" id="edit_subscription_{{preference.pk}}" class="modal-async" data-target='#notification_preference_modals' data-url="{% url 'notifications:edit-subscription' preference.pk %}"><span class="glyphicon glyphicon-pencil" title="{% trans "Edit" %}"></span></a></td>
                      <td><form id='unsubscribe_{{preference.pk}}' name='delete' action="{% url 'notifications:unsubscribe' preference.pk %}" method='POST'>
		                    {% csrf_token %}
		                    <button type='submit' class='btn btn-xs btn-link icon' title="{% trans 'Unsubscribe' %}"><i class='glyphicon glyphicon-remove'></i></button>
                          </form>
                      </td>
                  </tr>
              {% endfor %}
            </tbody>
          </table>
          <button id="subscribe_notification" class="modal-async btn btn-primary pull-right" type="button" data-target='#notification_preference_modals' data-url="{% url 'notifications:subscribe' %}"><span class="glyphicon glyphicon-plus" title="{% trans "Subscribe" %}"></span>&nbsp;{% trans "Subscribe" %}</button>
        </div>
      </div>
</div>
<div id='notification_preference_modals'>
</div>
<script src="{% static "fir_notifications/notifications.js" %}"></script>