fir_alerting/urls.py
from django.conf.urls import url

from fir_alerting import views

urlpatterns = [
    url(r'^(?P<incident_id>\d+)/get_template/(?P<template_type>[\w-]+)/$', views.get_template, name='get_template'),
    url(r'^(?P<incident_id>\d+)/get_template/(?P<template_type>[\w-]+)/(?P<bl>[\d]+)/$', views.get_template, name='get_template'),
    url(r'^emailform/$', views.emailform, name='emailform'),
    url(r'^send_email/$', views.send_email, name='send_email'),
]

fir_alerting/models.py
from django.db import models
from django import forms

from incidents.models import IncidentCategory, BusinessLine


class RecipientTemplate(models.Model):
    name = models.CharField(max_length=100)
    type = models.CharField(max_length=100)
    behalf = models.CharField(max_length=100)
    recipient_to = models.TextField()
    recipient_cc = models.TextField()
    recipient_bcc = models.TextField(null=True, blank=True)
    business_line = models.ForeignKey(BusinessLine, null=True, blank=True)

    def __unicode__(self):
        return self.name

    class Meta:
        db_table = 'incidents_recipienttemplate'


class CategoryTemplate(models.Model):
    name = models.CharField(max_length=100)
    type = models.CharField(max_length=100)
    body = models.TextField(help_text="This is a Markdown field. You can use django templating language.")
    subject = models.TextField()
    incident_category = models.ForeignKey(IncidentCategory)

    def __unicode__(self):
        return self.name

    class Meta:
        db_table = 'incidents_categorytemplate'


class EmailForm(forms.Form):
    behalf = forms.CharField()
    to = forms.CharField()
    cc = forms.CharField()
    bcc = forms.CharField()
    subject = forms.CharField()
    body = forms.CharField(widget=forms.Textarea)

fir_alerting/views.py
from django.contrib.auth.decorators import login_required, user_passes_test
from django.shortcuts import render, get_object_or_404
from django.db.models import Q
from django.template import Context
from django.http import HttpResponse, HttpResponseBadRequest
from django.template import Template
from json import dumps

from incidents.authorization.decorator import authorization_required
from incidents.views import is_incident_handler
from incidents.models import Incident, BusinessLine

from fir_alerting.models import RecipientTemplate, CategoryTemplate, EmailForm
from fir_email.helpers import send


def get_rec_template(query):
    template = list(RecipientTemplate.objects.filter(query))

    if len(template) > 0:
        return template[0]
    else:
        return None


@login_required
def emailform(request):
    email_form = EmailForm()

    return render(request, 'fir_alerting/emailform.html', {'form': email_form})


@login_required
@authorization_required('incidents.handle_incidents', Incident, view_arg='incident_id')
def get_template(request, incident_id, template_type, bl=None, authorization_target=None):
    if authorization_target is None:
        i = get_object_or_404(Incident.authorization.for_user(request.user, 'incidents.handle_incidents'),
                              pk=incident_id)
    else:
        i = authorization_target

    try:
        cat_template = CategoryTemplate.objects.get(incident_category=i.category, type=template_type)
    except Exception, e:
        cat_template = None

    rec_template = None

    if not bl:
        q_bl = Q(business_line__in=i.concerned_business_lines.all())
        bl_name = i.get_business_lines_names()
    else:
        bl = get_object_or_404(BusinessLine, pk=bl)
        q_bl = Q(business_line=bl)
        bl_name = bl.name

    rec_template = get_rec_template(q_bl & Q(type=template_type))

    parents = list(set(i.concerned_business_lines.all()))

    while not rec_template and len(parents):
        parents = list(set([b.get_parent() for b in parents if not b.is_root()]))
        q_parents = Q(business_line__in=parents)

        rec_template = get_rec_template(q_parents & Q(type=template_type))

    if rec_template is None:
        rec_template = get_rec_template(Q(business_line=None) & Q(type=template_type))

    artifacts = {}
    main_artifact = None
    for a in i.artifacts.all():
        if i.subject.lower() == a.value:
            main_artifact = a
        if a.type not in artifacts:
            artifacts[a.type] = []
        artifacts[a.type].append(a.value.replace('http://', "hxxp://").replace('https://', 'hxxps://'))

    enrich = None
    if main_artifact and main_artifact.artifactenrichment_set.all().count() > 0:
        enrich = main_artifact.artifactenrichment_set.all()[0].raw

    c = Context({
        'subject': i.subject.replace('http://', "hxxp://").replace('https://', 'hxxps://'),
        'bl': bl_name,
        'phishing_url': i.subject.replace('http://', "hxxp://").replace('https://', 'hxxps://'),
        'artifacts': artifacts,
        'incident_id': i.id,
        'enrich': enrich
    })

    response = {
        'behalf': rec_template.behalf if rec_template else "",
        'to': rec_template.recipient_to if rec_template else "",
        'cc': rec_template.recipient_cc if rec_template else "",
        'bcc': rec_template.recipient_bcc if rec_template else "",
        'subject': Template(cat_template.subject).render(c) if cat_template else "",
        'body': Template(cat_template.body).render(c) if cat_template else "",
        'bl': bl_name,
    }

    return HttpResponse(dumps(response), content_type="application/json")


@login_required
@user_passes_test(is_incident_handler)
def send_email(request):
    if request.method == 'POST':
        try:
            send(
                request,
                to=request.POST['to'],
                subject=request.POST['subject'],
                body=request.POST['body'],
                cc=request.POST['cc'],
                bcc=request.POST['bcc'],
                behalf=request.POST['behalf']
            )

            return HttpResponse(dumps({'status': 'ok'}), content_type="application/json")

        except Exception, e:
            return HttpResponse(dumps({'status': 'ko', 'error': str(e)}), content_type="application/json")

    return HttpResponseBadRequest(dumps({'status': 'ko'}), content_type="application/json")

fir_alerting/templates/fir_alerting/emailform.html
{% load i18n %}
{% load markdown %}
<div id="sendEmail" class="modal" tabindex="-1" role="dialog" aria-labelledby="sendEmailLabel" aria-hidden="true">
	<div class="modal-dialog modal-lg">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h4 id="sendEmailLabel" class="modal-title">{% trans "Send email" %}</h4>
			</div>

			<form id="email_form" action="{% url 'alerting:send_email' %}" method="POST" class='form-horizontal'>
				<div class="modal-body">
					{% csrf_token %}
					<div class='form-group nomargin'>
						<label for="id_behalf" class="col-sm-1 text-right">{% trans "From:" %}</label>
						<div class='col-sm-11'>
							{{ form.behalf }}
						</div>
					</div>
					<div class='form-group nomargin'>
						<label for="id_to" class="col-sm-1 text-right">{% trans "To:" %}</label>
						<div class='col-sm-11'>
							{{ form.to }}
						</div>
					</div>
					<div class='form-group nomargin'>
						<label for="id_cc" class="col-sm-1 text-right">{% trans "CC:" %}</label>
						<div class='col-sm-11'>
							{{ form.cc }}
						</div>
					</div>
					<div class='form-group nomargin'>
						<label for="id_bcc" class="col-sm-1 text-right">{% trans "BCC:" %}</label>
						<div class='col-sm-11'>
							{{ form.bcc }}
						</div>
					</div>
					<div class='form-group'>
						<label for="id_subject" class="col-sm-1 text-right">{% trans "Subject" %}</label>
						<div class='col-sm-11'>
							{{ form.subject|safe }}
						</div>
					</div>
					<div class='form-group'>
						<label for="id_body" class="col-sm-1 text-right">{% trans "Body" %}</label>
						<div class='col-sm-11'>
							{% rich_edit form.body %}
						</div>
					</div>
				</div>
			</form>

			<div class="modal-footer">
				<button class="btn btn-default" data-dismiss="modal" aria-hidden="true">{% trans "Close" %}</button>
				<button data-sent-text="Message sent" data-loading-text="Sending..." id='send_email' class="btn btn-primary">{% trans "Send email" %}</button>
			</div>
		</div>
	</div>
</div>

fir_alerting/templates/fir_alerting/plugins/details_actions.html
{% load i18n %}
{% load authorization %}
{% if event.concerned_business_lines.count == 1 %}
	{% with event.concerned_business_lines.all|first as bl %}
        {% has_perm 'incidents.handle_incidents' obj=bl as can_handle_incident %}
        {% if can_handle_incident %}
		<li>
			<a href='#' id='details-actions-alert' data-type='alerting' data-url="{% url 'alerting:get_template' event.id 'alerting' bl.id %}">
				<i class="glyphicon glyphicon-send"></i>{% trans "Alert" %}
			</a>
		</li>
        {% endif %}
	{% endwith %}
{% else %}
	{% has_perm 'incidents.handle_incidents' obj=event as can_handle_incident %}
	{% if can_handle_incident %}
		<li>
			<a href="#" id='details-actions-alert' data-type='alerting'>
				<i class="glyphicon glyphicon-send"></i>{% trans "Alert" %}
			</a>
		</li>
	{% endif %}
{% endif %}
{% has_perm 'incidents.handle_incidents' obj=event as can_handle_incident %}
{% if can_handle_incident %}
<li><a href="#" class='details-alert-bl' data-type='takedown' data-url="{% url 'alerting:get_template' event.id 'takedown' %}"><i class="glyphicon glyphicon-screenshot"></i>{% trans "Takedown" %}</a></li>
{% endif %}

fir_alerting/templates/fir_alerting/plugins/details_actions_menu.html
{% load authorization %}
<div class="details-actions-supmenu" id="details-actions-alert-bls" data-url="{% url 'alerting:emailform' %}">
	<ul class="list-unstyled">
		{% for bl in event.concerned_business_lines.all %}
            {% has_perm 'incidents.handle_incidents' obj=bl as can_handle_incident %}
            {% if can_handle_incident %}
							<li>
								<a href="#" class='details-alert-bl' data-target='#sendEmail' data-type='alerting' data-toggle='modal' data-url="{% url 'alerting:get_template' event.id 'alerting' bl.id %}">
									<i class="glyphicon glyphicon-send"></i>{{bl.name}}
								</a>
							</li>
            {% endif %}
		{% endfor %}
	</ul>
</div>

fir_alerting/templates/fir_alerting/plugins/details_static.html
{% load staticfiles %}
<script src="{% static "fir_alerting/js/alerting.js" %}"></script>
<link href="{% static "fir_alerting/css/alerting.css" %}" rel="stylesheet" />